config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :reviews

  root "reviews#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title , presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController  
  
  def index

    @reviews = Review.all
    
  end
  
  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(form_params)
    
    @review.save
    
    redirect_to root_path
  end
  
  def show
    @review = Review.find(params[:id])
  end
  
  
  def destroy
    @review = Review.find(params[:id])
    
    @review.destroy
    
    redirect_to root_path
  end
  
  def edit
    @review = Review.find(params[:id])
  end
  
  def update
    @review = Review.find(params[:id])
    
    @review.update(form_params)
    
    redirect_to review_path(@review)
  end
  
  def form_params
    params.require(:review).permit(:title, :body, :score)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bien Reviews – best restaurants in the world</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
          <% end %>
        </h1>        
      </nav>
      <nav>
        <%= link_to "Add a review", new_review_path %>
      </nav>
    </header>    
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      Copyright 2017 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
    
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>
    
    <p>
      <%= f.label :score %>
      <%= f.number_field :score %>
    </p>
    
    <%= f.submit "Save review" %>
  
  <% end %>

app/views/reviews/edit.html.erb
<h3>Edit your restaurant review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <div class="review">
    <%= link_to review.title, review_path(review) %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h3>Add your new restaurant review!</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1>

<div class="score">
  <%= @review.score %> / 10
</div>

<div class="body">
  <%= simple_format @review.body %>
</div>

<div class="actions">
  <%= link_to "Edit this review", edit_review_path(@review) %>
  <%= link_to "Delete this review", review_path(@review), method: :delete, data: { confirm: "Are you sure??" } %>
</div>